DROP TABLE product_report CASCADE CONSTRAINTS;
DROP TABLE report CASCADE CONSTRAINTS;
DROP TABLE payment CASCADE CONSTRAINTS;
DROP TABLE favourite_product CASCADE CONSTRAINTS;
DROP TABLE favourite CASCADE CONSTRAINTS;
DROP TABLE review CASCADE CONSTRAINTS;
DROP TABLE discount CASCADE CONSTRAINTS;
DROP TABLE order_product CASCADE CONSTRAINTS;
DROP TABLE orders CASCADE CONSTRAINTS;
DROP TABLE cart_product CASCADE CONSTRAINTS;
DROP TABLE cart CASCADE CONSTRAINTS;
DROP TABLE product CASCADE CONSTRAINTS;
DROP TABLE product_category CASCADE CONSTRAINTS;
DROP TABLE shop CASCADE CONSTRAINTS;
DROP TABLE coupon CASCADE CONSTRAINTS;
DROP TABLE collection_slot CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;

CREATE TABLE users (
user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
firstname VARCHAR2(50),
lastname VARCHAR2(50),
email VARCHAR2(100) UNIQUE,
contact_no VARCHAR2(20),
password VARCHAR2(200),
verification_code VARCHAR2(50),
role VARCHAR2(20),
created_date DATE,
status VARCHAR2(20)
);

CREATE TABLE shop (
shop_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
shop_name VARCHAR2(100),
registration_date DATE,
description VARCHAR2(500),
user_id NUMBER,
CONSTRAINT fk_shop_user
FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE product_category (
product_category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
category_type VARCHAR2(100)
);

CREATE TABLE collection_slot (
collection_slot_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
slot_day VARCHAR2(20),
slot_date DATE,
slot_time VARCHAR2(20),
total_order NUMBER
);

CREATE TABLE coupon (
coupon_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
coupon_title VARCHAR2(100),
coupon_offer VARCHAR2(200),
start_date DATE,
end_date DATE,
coupon_discount_percent NUMBER
);

CREATE TABLE product (
product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
product_name VARCHAR2(100),
description VARCHAR2(500),
price NUMBER(10,2),
quantity NUMBER,
stock_quantity NUMBER,
min_order NUMBER,
max_order NUMBER,
allergy_information VARCHAR2(200),
product_image VARCHAR2(200),
shop_id NUMBER,
product_category_id NUMBER,

CONSTRAINT fk_product_shop
FOREIGN KEY (shop_id) REFERENCES shop(shop_id),

CONSTRAINT fk_product_category
FOREIGN KEY (product_category_id) REFERENCES product_category(product_category_id)
);

CREATE TABLE cart (
cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
no_of_items NUMBER,
add_date DATE,
user_id NUMBER,

CONSTRAINT fk_cart_user
FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE favourite (
favourite_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
no_of_item NUMBER,
user_id NUMBER,

CONSTRAINT fk_favourite_user
FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE cart_product (
cart_id NUMBER,
product_id NUMBER,

CONSTRAINT pk_cart_product
PRIMARY KEY (cart_id, product_id),

CONSTRAINT fk_cp_cart
FOREIGN KEY (cart_id) REFERENCES cart(cart_id),

CONSTRAINT fk_cp_product
FOREIGN KEY (product_id) REFERENCES product(product_id)
);

CREATE TABLE discount (
discount_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
discount_percentage NUMBER,
product_id NUMBER,

CONSTRAINT fk_discount_product
FOREIGN KEY (product_id) REFERENCES product(product_id)
);


CREATE TABLE review (
review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
review VARCHAR2(500),
review_rating NUMBER,
user_id NUMBER,
product_id NUMBER,

CONSTRAINT fk_review_user
FOREIGN KEY (user_id) REFERENCES users(user_id),

CONSTRAINT fk_review_product
FOREIGN KEY (product_id) REFERENCES product(product_id)
);

CREATE TABLE orders (
order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
order_status VARCHAR2(50),
order_amount NUMBER(10,2),
order_date DATE,
order_quantity NUMBER,
collection_slot_id NUMBER,
coupon_id NUMBER,
cart_id NUMBER,

CONSTRAINT fk_order_slot
FOREIGN KEY (collection_slot_id) REFERENCES collection_slot(collection_slot_id),

CONSTRAINT fk_order_coupon
FOREIGN KEY (coupon_id) REFERENCES coupon(coupon_id),

CONSTRAINT fk_order_cart
FOREIGN KEY (cart_id) REFERENCES cart(cart_id)
);

CREATE TABLE order_product (
order_id NUMBER,
product_id NUMBER,

CONSTRAINT pk_order_product
PRIMARY KEY (order_id, product_id),

CONSTRAINT fk_op_order
FOREIGN KEY (order_id) REFERENCES orders(order_id),

CONSTRAINT fk_op_product
FOREIGN KEY (product_id) REFERENCES product(product_id)
);

CREATE TABLE payment (
payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
payment_date DATE,
payment_amount NUMBER(10,2),
payment_method VARCHAR2(50),
user_id NUMBER,
order_id NUMBER,

CONSTRAINT fk_payment_user
FOREIGN KEY (user_id) REFERENCES users(user_id),

CONSTRAINT fk_payment_order
FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

CREATE TABLE report (
report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
report_type VARCHAR2(100),
report_date DATE,
report_title VARCHAR2(200),
user_id NUMBER,
order_id NUMBER,

CONSTRAINT fk_report_user
FOREIGN KEY (user_id) REFERENCES users(user_id),

CONSTRAINT fk_report_order
FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

CREATE TABLE favourite_product (
product_id NUMBER,
favourite_id NUMBER,
added_date DATE,

CONSTRAINT pk_favourite_product
PRIMARY KEY (product_id, favourite_id),

CONSTRAINT fk_fp_product
FOREIGN KEY (product_id) REFERENCES product(product_id),

CONSTRAINT fk_fp_favourite
FOREIGN KEY (favourite_id) REFERENCES favourite(favourite_id)
);

CREATE TABLE product_report (
product_id NUMBER,
report_id NUMBER,

CONSTRAINT pk_product_report
PRIMARY KEY (product_id, report_id),

CONSTRAINT fk_pr_product
FOREIGN KEY (product_id) REFERENCES product(product_id),

CONSTRAINT fk_pr_report
FOREIGN KEY (report_id) REFERENCES report(report_id)
);


/* Values */
INSERT INTO users VALUES (1,'Admin','System','admin@cleckbasket.com','9800000001','admin123','V001','ADMIN',DATE '2025-08-01','ACTIVE');
INSERT INTO users VALUES (2,'John','Butcher','john@butcher.com','9800000002','pass123','V002','TRADER',DATE '2026-01-04','ACTIVE');
INSERT INTO users VALUES (3,'Sarah','Greengrocer','sarah@green.com','9800000003','pass122','V003','TRADER',DATE '2026-02-06','ACTIVE');
INSERT INTO users VALUES (4,'Michael','Fishmonger','michael@fish.com','9800000004','pass121','V004','TRADER',DATE '2026-02-22','ACTIVE');
INSERT INTO users VALUES (5,'Emily','Bakery','emily@bakery.com','9800000005','pass124','V005','TRADER',DATE '2026-02-28','ACTIVE');
INSERT INTO users VALUES (6,'David','Customer','david@gmail.com','9800000006','pass125','V006','CUSTOMER',DATE '2026-01-07','ACTIVE');
INSERT INTO users VALUES (7,'Lily','Customer','lil@gmail.com','9800000008','pass126','V008','CUSTOMER',DATE '2026-03-22','ACTIVE');

INSERT INTO shop VALUES (1,'Butcher Shop',DATE '2025-11-15','Fresh meat products',2);
INSERT INTO shop VALUES (2,'Green Grocery',DATE '2026-01-10','Fresh vegetables and fruits',3);
INSERT INTO shop VALUES (3,'Fish Market',DATE '2026-02-24','Seafood and fish products',4);
INSERT INTO shop VALUES (4,'Bakery House',DATE '2026-02-02','Bread and bakery items',5);
INSERT INTO shop VALUES (5,'Delicatessen',DATE '2026-03-15','Specialty foods and cheese',2);

INSERT INTO product_category VALUES (1,'Meat');
INSERT INTO product_category VALUES (2,'Vegetables');
INSERT INTO product_category VALUES (3,'Fish');
INSERT INTO product_category VALUES (4,'Bakery');
INSERT INTO product_category VALUES (5,'Dairy');
INSERT INTO product_category VALUES (6,'Fruits');
INSERT INTO product_category VALUES (7,'Seafood');
INSERT INTO product_category VALUES (8,'Snacks');

INSERT INTO collection_slot VALUES (1,'Wednesday',DATE '2026-02-16','10-13',5);
INSERT INTO collection_slot VALUES (2,'Friday',DATE '2025-10-10','13-16',4);
INSERT INTO collection_slot VALUES (3,'Wednesday',DATE '2026-02-06','16-19',6);
INSERT INTO collection_slot VALUES (4,'Thursday',DATE '2026-08-08','10-13',3);
INSERT INTO collection_slot VALUES (5,'Wednesday',DATE '2026-03-04','13-16',2);
INSERT INTO collection_slot VALUES (6,'Thursday',DATE '2026-03-20','16-19',4);
INSERT INTO collection_slot VALUES (7,'Friday',DATE '2026-02-19','10-13',7);
INSERT INTO collection_slot VALUES (8,'Wednesday',DATE '2026-03-03','13-16',5);

INSERT INTO coupon VALUES (1,'WELCOME10','New user discount',DATE '2025-11-09',DATE '2026-01-04',10);
INSERT INTO coupon VALUES (2,'FRESH5','Fresh food discount',DATE '2026-03-01',DATE '2026-03-02',5);
INSERT INTO coupon VALUES (3,'MEAT15','Meat special offer',DATE '2026-01-12',DATE '2026-01-18',15);
INSERT INTO coupon VALUES (4,'SEA10','Seafood discount',DATE '2026-03-09',DATE '2026-03-11',10);
INSERT INTO coupon VALUES (5,'BAKE5','Bakery discount',DATE '2026-02-17',DATE '2026-02-19',5);
INSERT INTO coupon VALUES (6,'FRUIT10','Fruit discount',DATE '2026-01-27',DATE '2026-02-02',10);
INSERT INTO coupon VALUES (7,'DAIRY8','Dairy product discount',DATE '2026-02-21',DATE '2026-02-22',8);
INSERT INTO coupon VALUES (8,'SNACK5','Snack discount',DATE '2026-03-18',DATE '2026-03-19',5);


INSERT INTO product VALUES 
(1,'Beef Steak','Fresh beef steak',12.50,10,10,1,5,'None','beef.png',1,1);

INSERT INTO product VALUES 
(2,'Pork Chops','Tender pork chops',10.00,15,15,1,5,'None','pork.png',1,1);

INSERT INTO product VALUES 
(3,'Red Apple','Fresh red apples',2.50,50,50,1,10,'None','apple.png',2,6);

INSERT INTO product VALUES 
(4,'Carrot','Organic carrots',1.50,40,40,1,10,'None','carrot.png',2,2);

INSERT INTO product VALUES 
(5,'Salmon','Fresh salmon fillet',15.00,20,20,1,5,'Fish allergy','salmon.png',3,3);

INSERT INTO product VALUES 
(6,'Shrimp','Wild-caught shrimp',20.00,25,25,1,5,'Shellfish','shrimp.png',3,7);

INSERT INTO product VALUES 
(7,'Whole Grain Bread','Healthy bread',3.50,30,30,1,10,'Gluten','bread.png',4,4);

INSERT INTO product VALUES 
(8,'Croissant','Buttery croissant',2.00,40,40,1,10,'Gluten','croissant.png',4,4);

INSERT INTO product VALUES 
(9,'Cheddar Cheese','Aged cheddar cheese',5.00,25,25,1,5,'Dairy','cheese.png',5,5);

INSERT INTO product VALUES 
(10,'Yogurt','Plain yogurt',2.50,30,30,1,10,'Dairy','yogurt.png',5,5);

INSERT INTO cart VALUES (1,2,DATE '2026-01-02',6);
INSERT INTO cart VALUES (2,3,DATE '2026-02-09',7);
INSERT INTO cart VALUES (3,1,DATE '2026-01-04',6);
INSERT INTO cart VALUES (4,2,DATE '2026-02-17',6);
INSERT INTO cart VALUES (5,4,DATE '2026-03-03',7);
INSERT INTO cart VALUES (6,1,DATE '2026-01-19',6);
INSERT INTO cart VALUES (7,3,DATE '2026-02-12',6);
INSERT INTO cart VALUES (8,2,DATE '2026-03-08',7);

INSERT INTO favourite VALUES (1,2,6);
INSERT INTO favourite VALUES (2,3,7);
INSERT INTO favourite VALUES (3,1,6);
INSERT INTO favourite VALUES (4,2,7);
INSERT INTO favourite VALUES (5,4,6);
INSERT INTO favourite VALUES (6,1,7);
INSERT INTO favourite VALUES (7,3,6);
INSERT INTO favourite VALUES (8,2,7);

INSERT INTO orders VALUES (1,'COMPLETED',25.50,DATE '2026-01-04',3,1,1,1); 
INSERT INTO orders VALUES (2,'PENDING',15.00,DATE '2026-02-07',2,2,2,2); 
INSERT INTO orders VALUES (3,'PROCESSING',20.00,DATE '2026-03-03',1,3,3,3); 
INSERT INTO orders VALUES (4,'COMPLETED',30.00,DATE '2026-03-02',4,4,4,4); 
INSERT INTO orders VALUES (5,'PENDING',18.50,DATE '2026-03-06',2,5,5,5); 
INSERT INTO orders VALUES (6,'COMPLETED',22.00,DATE '2026-02-11',3,6,6,6); 
INSERT INTO orders VALUES (7,'PROCESSING',12.00,DATE '2026-02-15',1,7,7,7); 
INSERT INTO orders VALUES (8,'COMPLETED',27.00,DATE '2026-03-06',2,8,8,8);

INSERT INTO cart_product VALUES (1,1);
INSERT INTO cart_product VALUES (2,3);
INSERT INTO cart_product VALUES (3,5);
INSERT INTO cart_product VALUES (4,7);
INSERT INTO cart_product VALUES (5,2);
INSERT INTO cart_product VALUES (6,6);
INSERT INTO cart_product VALUES (7,8);
INSERT INTO cart_product VALUES (8,9);

INSERT INTO order_product VALUES (1,1); 
INSERT INTO order_product VALUES (2,2); 
INSERT INTO order_product VALUES (3,3); 
INSERT INTO order_product VALUES (4,4); 
INSERT INTO order_product VALUES (5,5); 
INSERT INTO order_product VALUES (6,6); 
INSERT INTO order_product VALUES (7,7); 
INSERT INTO order_product VALUES (8,9);

INSERT INTO discount VALUES (1,10,1);
INSERT INTO discount VALUES (2,5,2);
INSERT INTO discount VALUES (3,8,3);
INSERT INTO discount VALUES (4,12,4);
INSERT INTO discount VALUES (5,15,5);
INSERT INTO discount VALUES (6,7,6);
INSERT INTO discount VALUES (7,6,7);
INSERT INTO discount VALUES (8,9,8);

INSERT INTO review VALUES (1,'Very fresh beef steak',5,6,1);
INSERT INTO review VALUES (2,'Good quality pork chops',4,7,2);
INSERT INTO review VALUES (3,'Apples were sweet',5,6,3);
INSERT INTO review VALUES (4,'Carrots very fresh',4,7,4);
INSERT INTO review VALUES (5,'Excellent salmon',5,6,5);
INSERT INTO review VALUES (6,'Shrimp tasted great',4,7,6);
INSERT INTO review VALUES (7,'Bread was soft',5,6,7);
INSERT INTO review VALUES (8,'Cheese quality nice',4,7,9);




INSERT INTO payment VALUES (1,DATE '2026-01-04',25.50,'CARD',6,1);
INSERT INTO payment VALUES (2,DATE '2026-02-07',15.00,'CASH',7,2);
INSERT INTO payment VALUES (3,DATE '2026-03-03',20.00,'CARD',6,3);
INSERT INTO payment VALUES (4,DATE '2026-03-02',30.00,'ESEWA',7,4);
INSERT INTO payment VALUES (5,DATE '2026-03-06',18.50,'CARD',6,5);
INSERT INTO payment VALUES (6,DATE '2026-02-11',22.00,'CASH',7,6);
INSERT INTO payment VALUES (7,DATE '2026-02-15',12.00,'ESEWA',6,7);
INSERT INTO payment VALUES (8,DATE '2026-03-06',27.00,'CARD',7,8);

INSERT INTO report VALUES (1,'Sales',DATE '2026-01-10','January Sales Report',1,1);
INSERT INTO report VALUES (2,'Customer',DATE '2026-02-15','Customer Feedback Report',1,2);
INSERT INTO report VALUES (3,'Inventory',DATE '2026-03-01','Stock Status Report',1,3);
INSERT INTO report VALUES (4,'Sales',DATE '2026-03-05','Weekly Sales Summary',1,4);
INSERT INTO report VALUES (5,'Order',DATE '2026-03-06','Pending Orders Report',1,5);
INSERT INTO report VALUES (6,'Delivery',DATE '2026-02-20','Delivery Status Report',1,6);
INSERT INTO report VALUES (7,'Finance',DATE '2026-02-25','Payment Summary Report',1,7);
INSERT INTO report VALUES (8,'System',DATE '2026-03-07','System Activity Report',1,8);

INSERT INTO favourite_product VALUES (1,1,DATE '2026-01-05');
INSERT INTO favourite_product VALUES (3,2,DATE '2026-02-09');
INSERT INTO favourite_product VALUES (5,3,DATE '2026-02-11');
INSERT INTO favourite_product VALUES (7,4,DATE '2026-03-01');
INSERT INTO favourite_product VALUES (2,5,DATE '2026-03-03');
INSERT INTO favourite_product VALUES (6,6,DATE '2026-02-15');
INSERT INTO favourite_product VALUES (8,7,DATE '2026-02-20');
INSERT INTO favourite_product VALUES (9,8,DATE '2026-03-05');

INSERT INTO product_report VALUES (1,1);
INSERT INTO product_report VALUES (2,2);
INSERT INTO product_report VALUES (3,3);
INSERT INTO product_report VALUES (4,4);
INSERT INTO product_report VALUES (5,5);
INSERT INTO product_report VALUES (6,6);
INSERT INTO product_report VALUES (7,7);
INSERT INTO product_report VALUES (9,8);
