<?php
if (session_status() === PHP_SESSION_NONE) { session_start(); }
$_SESSION['user_id'] = $_SESSION['user_id'] ?? 1;
$_SESSION['role'] = $_SESSION['role'] ?? 'trader';
$_SESSION['full_name'] = $_SESSION['full_name'] ?? 'Unus';
function h($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>My Products</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><link rel="stylesheet" href="trader_frontend.css"></head><body><header class="cb-topbar"><a class="cb-brand" href="traderdashboard.php"><i class="fa-solid fa-cart-shopping"></i><div><strong>CLECK BASKET</strong><span>SHOP LOCAL · EAT FRESH</span></div></a><nav><a href="traderdashboard.php">Home</a><a href="My_products.php">Shop</a><a href="#">About</a><a href="#">Contact Us</a></nav><div class="cb-search">What do you need today? <i class="fa-solid fa-magnifying-glass"></i></div><div class="cb-user"><i class="fa-regular fa-user"></i><span>Hi, <?=h($_SESSION['full_name'])?>!</span></div></header><aside class="cb-sidebar"><a class="" href="traderdashboard.php"><i class="fa-solid fa-border-all"></i>Dashboard</a><a class="active" href="add_product.php"><i class="fa-regular fa-square-plus"></i>Management</a><a class="" href="trader_profile.php"><i class="fa-solid fa-gear"></i>Settings</a></aside><main class="page">
<?php $products=[['PRODUCT_ID'=>1,'PRODUCT_NAME'=>'Heirloom Tomatoes','SHOP_NAME'=>'Mir Farm','SHOP_CATEGORY'=>'Vegetables','PRICE'=>3.50,'STOCK'=>84,'PRODUCT_STATUS'=>'In Stock','PRODUCT_IMAGE'=>''],['PRODUCT_ID'=>2,'PRODUCT_NAME'=>'Artisan Sourdough','SHOP_NAME'=>'Mir Farm','SHOP_CATEGORY'=>'Bakery','PRICE'=>4.20,'STOCK'=>12,'PRODUCT_STATUS'=>'Low Stock','PRODUCT_IMAGE'=>''],['PRODUCT_ID'=>3,'PRODUCT_NAME'=>'Whole Farm Milk (2L)','SHOP_NAME'=>'Mir Farm','SHOP_CATEGORY'=>'Dairy','PRICE'=>2.30,'STOCK'=>45,'PRODUCT_STATUS'=>'In Stock','PRODUCT_IMAGE'=>'']]; ?>
<div class="page-head"><div><p>TRADER PORTAL › INVENTORY</p><h1>My Products</h1></div><a class="btn" href="add_product.php"><i class="fa-solid fa-plus"></i>Add Product</a></div><div class="grid"><?php foreach($products as $p): ?><div class="card"><div style="height:160px;background:#f1eeee;border-radius:18px;display:grid;place-items:center;margin-bottom:18px"><i class="fa-regular fa-image" style="font-size:40px;color:#bbb"></i></div><h2><?=h($p['PRODUCT_NAME'])?></h2><p><?=h($p['SHOP_NAME'])?> · <?=h($p['SHOP_CATEGORY'])?></p><h2>£<?=number_format($p['PRICE'],2)?></h2><p class="<?=strtolower(str_replace(' ','-',$p['PRODUCT_STATUS']))?>"><?=h($p['STOCK'])?> units · <?=h($p['PRODUCT_STATUS'])?></p><a class="btn light" href="edit_product.php?id=<?=$p['PRODUCT_ID']?>">Edit</a> <button class="btn" onclick="alert('Front-end demo only: delete disabled')">Delete</button></div><?php endforeach; ?></div>
</main></body></html>